# MySQL 연결 정보
spring:
  datasource:
    url: jdbc:mysql://10.10.5.68:3306/kassy
    username: kassy
    password: P@ssw0rd!!@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    initialize-schema: always
    table-prefix: BATCH_